import { ROLES } from '../constants';

export const mockEmployees = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@electrolyte.com',
    role: ROLES.ADMIN,
    department: 'Management',
    phone: '+91-9876543210',
    status: 'active',
    joinedDate: '2024-01-15',
    assignedInventory: [],
  },
  {
    id: '2',
    name: 'John Doe',
    email: 'employee@electrolyte.com',
    role: ROLES.EMPLOYEE,
    department: 'Production',
    phone: '+91-9876543211',
    status: 'active',
    joinedDate: '2024-01-20',
    assignedInventory: ['1', '2', '3'],
  },
  {
    id: '3',
    name: 'Jane Smith',
    email: 'jane.smith@electrolyte.com',
    role: ROLES.EMPLOYEE,
    department: 'Production',
    phone: '+91-9876543212',
    status: 'active',
    joinedDate: '2024-02-01',
    assignedInventory: ['4', '5'],
  },
  {
    id: '4',
    name: 'Mike Johnson',
    email: 'mike.johnson@electrolyte.com',
    role: ROLES.EMPLOYEE,
    department: 'Quality Control',
    phone: '+91-9876543213',
    status: 'active',
    joinedDate: '2024-02-05',
    assignedInventory: ['6', '7', '8'],
  },
  {
    id: '5',
    name: 'Sarah Williams',
    email: 'sarah.williams@electrolyte.com',
    role: ROLES.EMPLOYEE,
    department: 'Warehouse',
    phone: '+91-9876543214',
    status: 'inactive',
    joinedDate: '2024-01-10',
    assignedInventory: [],
  },
];
